---
title: "中文简历"
editor: 
  markdown: 
    wrap: 72
---

<!-- ## 个人简介 -->

陈家苇，女，博士在读。2022年毕业于哈尔滨工业大学（深圳）机电工程与自动化学院，获自动化专业工学学士学位。2022年秋季至今，就读于香港理工大学航空及民航工程学系，预计于2026年8月毕业。
研究方向为人工智能驱动的优化决策，预测控制等，成果见诸 *IEEE Transactions on Intelligent Transportation Systems*, *Management Science*, *Advanced Engineering Informatics*, *IEEE Transactions on Automation Science and Engineering* 等期刊。

- 邮箱：superlaser-jw.chen@connect.polyu.hk (优先); byzcj1205@gmail.com 
- 电话：852-96350935
- 地址：香港特别行政区，九龙红磡育才道11号，香港理工大学
- Github: <https://github.com/Jiawei-CHEN1205>
- 个人主页：<https://jiawei-chen1205.github.io/jiaweichen.github.io/>

## 教育和工作背景

- 2022.09-2026.08 (预计) 香港理工大学 航空及民航工程学系 博士
- 2018.09-2022.08 哈尔滨工业大学（深圳） 机电工程与自动化学院 自动化专业 本科

## 参与教学任务
- AAE3006 Safety, Reliability and Compliance (本科)
- AAE5103 Artificial Intelligence in Aviation Industry (硕士)

## 研究兴趣

- Reinforcement Learning for Combinatorial Optimization
- Data-driven Optimization and Control
- Healthcare \& Emergency Decision-Making
<!-- - Intelligent Transportation Systems -->
- Cooperative AI
- Dynamic Optimization
<!-- 有待更新 -->



## 发表论文

-   **Chen, J.**, Wan, P., & Xu, G.^\*^ (2025). Cooperative Learning-Based Joint UAV and Human Courier Scheduling for Emergency Medical Delivery Service. *IEEE Transactions on Intelligent Transportation Systems*. [Link](https://doi.org/10.1109/tits.2024.3486789)
-   Liu, Y., Xie, B., Long, Y., **Chen, J.**, & Xu, G.^\*^ (2025). Learning-Based Heterogeneous Autonomous Vehicles Scheduling for On-Demand Last-Mile Transportation. *IEEE Transactions on Automation Science and Engineering*. [Link](https://doi.org/10.1109/TASE.2025.3611676)
-   Wan, P., Xu, G.^\*^, **Chen, J.**, & Zhou, Y. (2024). Deep Reinforcement Learning Enabled Multi-UAV Scheduling for Disaster Data Collection With Time-Varying Value. *IEEE Transactions on Intelligent Transportation Systems*. [Link](https://doi.org/10.1109/TITS.2023.3345280)
-   **Chen, J.**, Xu, G.^\*^, & Zhou, Z. (2023). Data-driven learning-based Model Predictive Control for energy-intensive systems. *Advanced Engineering Informatics*, 58, 102208–102208. [Link](https://doi.org/10.1016/J.AEI.2023.102208)
-   **Chen, J.**, Wan, P., Xu, G., & Shao, S. (2023). Collaborative Medical Delivery Service with UAVs and Human Couriers. *2023 IEEE International Conference on Industrial Engineering and Engineering Management (IEEM)*, 1340–1345. [Link](https://doi.org/10.1109/IEEM58616.2023.10406453)


<!-- ## 科研项目 -->

## 演讲 \& 座谈

- 第十三届机器人智能技术与应用国际会议 (RiTA 2025)：动态机器人舰队中任务重新分配的自适应深度强化学习，@ 伦敦国王学院，英国伦敦，2025.12.17-12.20
- 2025年POMS中国国际会议 (POMS China)：紧急医疗配送的无人机与人工快递员一体化系统，@ 海南省儋州市海花岛国际会议中心，中国，2025.07.12
- 香港理工大学航空航天工程学院航空研讨会：基于协同学习的紧急医疗配送无人机与人工快递员联合调度，\@ 香港理工大学，中国香港，2024.11.22.


## 科研服务

1. 期刊 \& 会议审稿人
- Engineering Applications of Artificial Intelligence (EAAI)
- IEEE Transactions on Automation Science and Engineering (T-ASE)
- IEEE Transactions on Intelligent Transportation Systems (T-ITS)
- IEEE Transactions on Industrial Informatics (TII)
2. 会议志愿者 \& 助理
- The 28th Air Transport Research Society (ATRS) World Conference，2025年7月 @ 中国香港

## 其他经历

- 算法实习生，[蘑菇物联](https://www.mogulinker.com/) @ 中国深圳，2022.05 – 2022.08
- 产品研发实习生，[深圳乐动机器人有限公司](https://www.ldrobot.com/) @ 中国深圳，2021.11 – 2022.04

