---
title: "Others"
editor: 
  markdown: 
    wrap: 72
---


## Invited Talk \& Presentation

- [13th International Conference on Robot Intelligence Technology and Applications (RiTA 2025)](https://icrita.org/): Adaptive Deep Reinforcement Learning for Task Reallocation in Dynamic Robotic Fleets, \@ King's College London, London, United Kingdom, 17-20 December, 2025
- [2025 POMS International Conference in China](https://poms.tju.edu.cn/): Integrated UAV and Human Courier System for Emergency Medical Delivery Service, \@ Ocean Flower Island International Conference Center in Danzhou City, Hainan Province, China, 12 July, 2025 
- PolyU AAE Aviation Workshop: Cooperative Learning-based Joint UAV and Human Courier Scheduling for Emergency Medical Delivery Service, \@ The Hong Kong Polytechnic University, Hong Kong SAR, China, 22 November, 2024 
- [2023 IEEM Conference](http://ieem2023.org/public.asp?page=index.asp): Collaborative medical delivery service with uavs and human couriers, \@ Marina Bay Sands, Singapore, 19 December, 2023


## Journal Reviewer
- Engineering Applications of Artificial Intelligence (EAAI)
- IEEE Transactions on Automation Science and Engineering (T-ASE)
- IEEE Transactions on Intelligent Transportation Systems (T-ITS)
- IEEE Transactions on Industrial Informatics (TII)

## Volunteer \& Assistant

- Assistant, [The 28th Air Transport Research Society (ATRS) World Conference](https://www.atrsworld.org/home-3), July 2025 \@ Hong Kong
- Volunteer, [Shenzhen Volunteer Association](https://www.sva.org.cn/SZWSLDPC/#/), 2019 - 2022 \@ Shenzhen, China

## Honor \& Award

- PolyU Research Postgraduate Scholarship, 2022 - 2026
- HITSZ University Scholarship, 2018 - 2022
- Excellent Project Award, [XBOT PARK](https://en.xbotpark.com/) Smart C-end Scientific Innovation Training Camp (Team Leader), 2021
- First Prize, [National College Students' Mathematical Modeling Competition](https://www.mcm.edu.cn/) (Team Leader), 2020
- Second Prize, [11th National College Students' Mathematics Competition](http://www.cmathc.cn/) (Individual), 2020
- [Song Ching Ling Scholarship](https://www.sclf.org/gyxmx/gzxmz/sqljxj/202312/t20231220_28341.htm) (The only national-level scholarship for students in the nine-year compulsory education stage in China), 2014
<!-- - 举例一些best paper award, student paper award之类的 -->

## Teaching \& Tutorial

- AAE3006 Safety, Reliability and Compliance (Undergraduate)
- AAE5103 Artificial Intelligence in Aviation Industry (Master)

## Work Experience

- Algorithm Intern, [MoguLinker](https://www.mogulinker.com/)@Shenzhen, China, May 2022 - Aug 2022
- Product R&D Intern, [Shenzhen Ldrobot Co., Ltd.](https://www.ldrobot.com/)@Shenzhen, China, Nov 2021 - Apr 2022
