---
title: "Publications"
editor: visual
---

::: callout-note
## Links

> -   **Google Scholar**: <https://scholar.google.com/citations?user=KPtUwlYAAAAJ&hl=zh-CN>
> -   **ORCID**: <https://orcid.org/0000-0001-7653-4998>
> -   **ResearchGate:** <https://www.researchgate.net/profile/Jiawei-Chen-74>
:::

## Research Interests

-  Reinforcement Learning for Combinatorial Optimization
-  Data-driven Optimization and Control
-  Healthcare \& Emergency Decision-Making
<!-- -  Intelligent Transportation Systems -->
-  Cooperative AI
-  Dynamic Optimization

## Journal Paper

-   **Chen, J.**, Wan, P., & Xu, G.^\*^ (2025). Cooperative Learning-Based Joint UAV and Human Courier Scheduling for Emergency Medical Delivery Service. *IEEE Transactions on Intelligent Transportation Systems*. [Link](https://doi.org/10.1109/tits.2024.3486789)
-   Liu, Y., Xie, B., Long, Y., **Chen, J.**, & Xu, G.^\*^ (2025). Learning-Based Heterogeneous Autonomous Vehicles Scheduling for On-Demand Last-Mile Transportation. *IEEE Transactions on Automation Science and Engineering*. [Link](https://doi.org/10.1109/TASE.2025.3611676)
-   Wan, P., Xu, G.^\*^, **Chen, J.**, & Zhou, Y. (2024). Deep Reinforcement Learning Enabled Multi-UAV Scheduling for Disaster Data Collection With Time-Varying Value. *IEEE Transactions on Intelligent Transportation Systems*. [Link](https://doi.org/10.1109/TITS.2023.3345280)
-   **Chen, J.**, Xu, G.^\*^, & Zhou, Z. (2023). Data-driven learning-based Model Predictive Control for energy-intensive systems. *Advanced Engineering Informatics*, 58, 102208–102208. [Link](https://doi.org/10.1016/J.AEI.2023.102208)

## Conference Paper

-   **Chen, J.**, Wan, P., Xu, G.^\*^, & Shao, S. (2023). Collaborative Medical Delivery Service with UAVs and Human Couriers. *2023 IEEE International Conference on Industrial Engineering and Engineering Management (IEEM)*, 1340–1345. [Link](https://doi.org/10.1109/IEEM58616.2023.10406453)

## Working Paper

-   **Chen, J.**, Wan, P., & Xu, G.^\*^ (2025). Learning for Dynamic Mass Casualty Management with Multi-Function Teams. *Available at SSRN 5153712*. [Link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5153712)